//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akademik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MAHASISWA
    {
        public string NIM { get; set; }
        [Required(ErrorMessage = "This Field is Required")] //validasi di sisi db
        public string NAMA_MHS { get; set; }
        [Required(ErrorMessage = "This Field is Required")] //validasi di sisi db

        public Nullable<System.DateTime> TGL_LAHIR { get; set; }
        public string ALAMAT { get; set; }
        public string JENIS_KELAMIN { get; set; }
    }
}
