//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATAKULIAH
    {
        public string KODE_MK { get; set; }
        public string NAMA_MK { get; set; }
        public Nullable<int> SKS { get; set; }
    }
}
