//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akademik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PERKULIAHAN
    {
        public string NIM { get; set; }
        public string KODE_MK { get; set; }
        public string NIP { get; set; }
        public string NILAI { get; set; }
        
        [NotMapped]
        public List<MAHASISWA> namamahasiswa { get; set; }

        [NotMapped]
        public List<MATAKULIAH> listmk { get; set; }

        [NotMapped]
        public List<DOSEN> listdosen { get; set; }

       
    }
    

}
